// <auto-generated />
using System;
using AssetTracker.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AssetTracker.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525080710_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssetTracker.Domain.Entities.Bearing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Bearings");
                });

            modelBuilder.Entity("AssetTracker.Domain.Entities.LocationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("MotorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MotorId");

                    b.ToTable("LocationHistories");
                });

            modelBuilder.Entity("AssetTracker.Domain.Entities.LubricantType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("LubricantTypes");
                });

            modelBuilder.Entity("AssetTracker.Domain.Entities.MaintenanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BearingPosition")
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LubricantTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("MotorId")
                        .HasColumnType("integer");

                    b.Property<int?>("NewBearingId")
                        .HasColumnType("integer");

                    b.Property<int?>("OldBearingId")
                        .HasColumnType("integer");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("WorkType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LubricantTypeId");

                    b.HasIndex("NewBearingId");

                    b.HasIndex("OldBearingId");

                    b.HasIndex("MotorId", "WorkType", "BearingPosition", "Date")
                        .HasDatabaseName("IX_MaintenanceLogs_LastLubricant");

                    b.ToTable("MaintenanceLogs");
                });

            modelBuilder.Entity("AssetTracker.Domain.Entities.Motor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FrontBearingId")
                        .HasColumnType("integer");

                    b.Property<string>("InventoryNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MountingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double>("Power")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<int>("RearBearingId")
                        .HasColumnType("integer");

                    b.Property<double>("ShaftDiameter")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("FrontBearingId");

                    b.HasIndex("InventoryNumber")
                        .IsUnique()
                        .HasFilter("\"InventoryNumber\" IS NOT NULL");

                    b.HasIndex("RearBearingId");

                    b.ToTable("Motors");
                });

            modelBuilder.Entity("AssetTracker.Domain.Entities.LocationHistory", b =>
                {
                    b.HasOne("AssetTracker.Domain.Entities.Motor", "Motor")
                        .WithMany("LocationHistories")
                        .HasForeignKey("MotorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motor");
                });

            modelBuilder.Entity("AssetTracker.Domain.Entities.MaintenanceLog", b =>
                {
                    b.HasOne("AssetTracker.Domain.Entities.LubricantType", "LubricantType")
                        .WithMany()
                        .HasForeignKey("LubricantTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AssetTracker.Domain.Entities.Motor", "Motor")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("MotorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetTracker.Domain.Entities.Bearing", "NewBearing")
                        .WithMany()
                        .HasForeignKey("NewBearingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AssetTracker.Domain.Entities.Bearing", "OldBearing")
                        .WithMany()
                        .HasForeignKey("OldBearingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LubricantType");

                    b.Navigation("Motor");

                    b.Navigation("NewBearing");

                    b.Navigation("OldBearing");
                });

            modelBuilder.Entity("AssetTracker.Domain.Entities.Motor", b =>
                {
                    b.HasOne("AssetTracker.Domain.Entities.Bearing", "FrontBearing")
                        .WithMany()
                        .HasForeignKey("FrontBearingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssetTracker.Domain.Entities.Bearing", "RearBearing")
                        .WithMany()
                        .HasForeignKey("RearBearingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FrontBearing");

                    b.Navigation("RearBearing");
                });

            modelBuilder.Entity("AssetTracker.Domain.Entities.Motor", b =>
                {
                    b.Navigation("LocationHistories");

                    b.Navigation("MaintenanceLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
