apiVersion: apps/v1
kind: Deployment
metadata:
  name: assettracker-api
  namespace: uchaly
  labels:
    io.kompose.service: assettracker-api
  annotations:
    # ИСПРАВЛЕНО: Вместо "semver" указываем "minor" (или "patch")
    keel.sh/policy: minor
    # Включаем опрос реестра
    keel.sh/trigger: poll
    # Интервал опроса (каждые 20 минут)
    keel.sh/pollSchedule: "@every 20m"
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: assettracker-api
  template:
    metadata:
      labels:
        io.kompose.service: assettracker-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: assettracker-api
          image: ghcr.io/marat1905/assettracker-api:1.2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ConnectionStrings__DefaultConnection
              value: Host=assettracker-db;Port=5432;Database=assettracker;Username=postgresuser;Password=12345678
      restartPolicy: Always