apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: assettracker-api
  name: assettracker-api
spec:
  type: NodePort
  ports:
    - name: "http-web-api"
      nodePort: 30012
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: assettracker-api