apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: assettracker-api
  name: assettracker-api
  annotations:
    # Включаем автоматическое обновление
    keel.sh/policy: force
    # Keel будет проверять реестр ghcr.io каждые 10 минут
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 10m"
spec:
  replicas: 1 # Количество подов
  selector:
    matchLabels:
      io.kompose.service: assettracker-api
  template:
    metadata:
      labels:
        io.kompose.service: assettracker-api
    spec:
      # Важно: используем секрет для скачивания из GHCR
      imagePullSecrets:
      - name: ghcr-secret
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ConnectionStrings__DefaultConnection
              value: Host=assettracker-db;Port=5432;Database=assettracker;Username=postgresuser;Password=12345678
          image: ghcr.io/marat1905/assettracker-api:latest
          name: assettracker-api
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always