apiVersion: v1
kind: Service
metadata:
  name: assettracker-db
  namespace: uchaly
  labels:
    io.kompose.service: assettracker-db
spec:
  type: NodePort
  ports:
    - name: "tcp-db"
      nodePort: 30153
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: assettracker-db