apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assettracker-db-data
  namespace: uchaly
  labels:
    io.kompose.service: assettracker-db-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi